//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги_в_аренде
    {
        public int id { get; set; }
        public int id_Сотрудника { get; set; }
        public int id_Клиента { get; set; }
        public int id_Книги { get; set; }
        public System.DateTime Дата_получения { get; set; }
        public System.DateTime Дата_воврата { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Книги Книги { get; set; }
    }
}
