//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        public int id { get; set; }
        public int id_Поставщика { get; set; }
        public int id_Книги { get; set; }
        public string Количество { get; set; }
        public string Дата_поставки { get; set; }
        public int id_сотрудника { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
